### ISSUE TITLE
[Feature] getDenormalisedWeight

### ISSUE THREAD

**Issue by MickdeGraaf** [pie-dao/pie-smart-pools#26]
#### User Story

- As an <audience/user>: Dev interacting with the smart contract.
- I want to <action/task>: Be able to get the denormalised weight of a specific token in the underlying balancer pool.
- so that <outcome/goal/benefit>: So I don't have to call it directly.
#### Type

- [x] Enhancement
- [ ] Maintenance
- [ ] Refactor

#### Description

Calls the exact same function on the underlying pool contract.

#### Definition of Done

- [x] Implement `getDenormalizedWeight(address token)`
- [x] Sufficient test coverage in unit tests
- [ ] Tested in mainnet test

#### Attach files or screenshots if it's helpful for this issue.

Reference implementation: https://github.com/balancer-labs/smart-pools/blob/master/crp/contracts/ConfigurableRightsPool.sol#L112

**Comment by dmvt** [comment]
https://forum.piedao.org/t/bounty-program-votes/118/2
PieDAO governance has voted to approve this issue for a bounty:
Approved Scope: 4 - 8 hours (1397.6 - 2795.2 $DOUGH)
Contributor: [@travisdmathis](https://github.com/travisdmathis)

**Comment by dmvt** [comment]
Leaving this in done until we work out the disbursement

**Comment by MickdeGraaf** [comment]
Implemented in #51
