### ISSUE TITLE
[Feature] Throw error on unsupported methods from configurable rights pool

### ISSUE THREAD

**Issue by MickdeGraaf** [pie-dao/pie-smart-pools#27]
#### User Story

- As an <audience/user>: A dev integrating the Pie Smart Pools
- I want to <action/task>: Know that these methods are not supported
- so that <outcome/goal/benefit>: So I don't wonder why it's not working

#### Type

- [x] Enhancement
- [ ] Maintenance
- [ ] Refactor

#### Definition of Done

- [x] Throw error on: `function finalizeSmartPool()`
- [x] Throw error on: `function createPool()`
- [x] Errors clearly state that function is not supported
- [x] Test errors in unit test

#### Attach files or screenshots if it's helpful for this issue.

Reference Implementations:

- https://github.com/balancer-labs/smart-pools/blob/master/crp/contracts/ConfigurableRightsPool.sol#L170
- https://github.com/balancer-labs/smart-pools/blob/master/crp/contracts/ConfigurableRightsPool.sol#L160

**Comment by dmvt** [comment]
https://forum.piedao.org/t/bounty-program-votes/118/2
PieDAO governance has voted to approve this issue for a bounty:
Approved Scope: 4 - 8 hours (1397.6 - 2795.2 $DOUGH)
Contributor: [@travisdmathis](https://github.com/travisdmathis)

**Comment by travisdmathis** [comment]
leaving in done until disbursement

**Comment by MickdeGraaf** [comment]
Implemented in #51
