### ISSUE TITLE
[Feature] Single asset join

### ISSUE THREAD

**Issue by MickdeGraaf** [pie-dao/pie-smart-pools#30]
#### User Story

- As an <audience/user>: User
- I want to <action/task>: Add liquidity from a single asset
- so that <outcome/goal/benefit>: So I don't have to source all the individual tokens.

#### Type

- [x] Enhancement
- [ ] Maintenance
- [ ] Refactor

#### Definition of Done

- [x] `function joinswapExternAmountIn(address tokenIn, uint256 tokenAmountIn)`
- [x] `function joinswapPoolAmountOut(uint poolAmountOut, address tokenIn)`
- [x] Test coverage in unit tests for above functionality
- [x] Test above functionality in mainnet test

#### Attach files or screenshots if it's helpful for this issue.

Reference implementation: https://github.com/balancer-labs/smart-pools/blob/master/crp/contracts/ConfigurableRightsPool.sol

**Comment by dmvt** [comment]
https://forum.piedao.org/t/bounty-program-votes/118/2
PieDAO governance has voted to approve this issue for a bounty:
Approved Scope: 8 - 16 hours (2795.2 - 5590.4 $DOUGH)
Contributor: [@travisdmathis](https://github.com/travisdmathis)

**Comment by travisdmathis** [comment]
Leaving as done until paid out

**Comment by MickdeGraaf** [comment]
Implemented in #51
