### ISSUE TITLE
[Feature] Remove liquidity from a single asset

### ISSUE THREAD

**Issue by MickdeGraaf** [pie-dao/pie-smart-pools#31]
#### User Story

- As an <audience/user>: User
- I want to <action/task>: Remove my liquidity in a single asset
- so that <outcome/goal/benefit>: So I don't have to liquidate all the unwanted assets

#### Type

- [x] Enhancement
- [ ] Maintenance
- [ ] Refactor

#### Definition of Done

- [x] `function exitswapPoolAmountIn(uint poolAmountIn, address tokenOut)`
- [x] `function exitswapExternAmountOut(address tokenOut, uint tokenAmountOut)`
- [x] Test coverage in unit test
- [x] Tested in mainnet test

#### Attach files or screenshots if it's helpful for this issue.

Reference implementation: https://github.com/balancer-labs/smart-pools/blob/master/crp/contracts/ConfigurableRightsPool.sol

**Comment by dmvt** [comment]
https://forum.piedao.org/t/bounty-program-votes/118/2
PieDAO governance has voted to approve this issue for a bounty:
Approved Scope: 8 - 16 hours (2795.2 - 5590.4 $DOUGH)
Contributor: [@travisdmathis](https://github.com/travisdmathis)

**Comment by travisdmathis** [comment]
Leaving these as done until I can be paid out for them

**Comment by MickdeGraaf** [comment]
Implemented in #51
